### ISSUE TITLE
Assert in generate.py needs to go...

### ISSUE THREAD

**Issue by RDouglasSharp** [Lightning-AI/lit-parrot#65]
generate.py line 45: assert max_seq_length <= T_new  breaks otherwise running training code.  There is no good reason for this assertion  IMHO. 

I need to run with a long max_seq_length, to learn from some longer passages in my instruction set.  Just because the specific instruction that is used in validation is shorter than the longest required is no reason to abort, and I discovered this assertion after about an hour of training.  With the assertion gone, and training restarted, everything is working...

**Comment by ArturK-85** [comment]
confirm, I also had a problem with fine tuning, when I removed the assert max_seq_length <= T_new breaks everything worked fine

**Comment by lantiga** [comment]
Thanks for bringing this up. Merged

**Comment by carmocca** [comment]
Removing the assertion is valid for the training case, but during generation, a max_seq_length higher than T_new would just allocate unnecessary memory.

Maybe we should ask that `T_new` becomes an input argument to `generate` so that we can have different validation in the generate and training scripts.

**Comment by lantiga** [comment]
Sounds good
